authentification/urls.py
from django.urls import path
from authentification.views import SigninView, SignupView,  SignoutView
from django.contrib.auth import  views as auth_views

app_name = 'authentification'

urlpatterns = [
    path('signin/', SigninView, name='signin'),
    path('signup/', SignupView, name='signup'),
    path("signout/", SignoutView, name = 'signout'),
    # path("login/", auth_views.LoginView.as_view(), name='login'),
]

conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('products/', include('products.urls', namespace='products')),
    path('auth/', include('authentification.urls', namespace='authentification')),
    path("blog/", include('blogs.urls', namespace='blogs')),
    path('orders/', include('orders.urls', namespace='orders')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/register/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="{% static 'auth/fonts/icomoon/style.css' %}" />

    <link
      rel="stylesheet"
      href="{% static 'auth/css/owl.carousel.min.css' %}"
    />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'auth/css/bootstrap.min.css' %}" />

    <!-- Style -->
    <link rel="stylesheet" href="{% static 'auth/css/style.css' %}" />

    <title>Signin</title>
  </head>
  <body>
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}

    <div class="d-md-flex half">
      <div
        class="bg"
        style="background-image: url('{% static 'auth/images/bg_1.jpg' %}')"
      ></div>
      <div class="contents">
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-12">
              <div class="form-block mx-auto">
                <div class="text-center mb-5">
                  <h3 class="text-uppercase">
                    Login to <strong>Colorlib</strong>
                  </h3>
                </div>
                <form
                  action="{% url 'authentification:signin' %}"
                  method="post"
                >
                  {% csrf_token %}
                  <div class="form-group first">
                    <label for="username">Username</label>
                    <input
                      type="text"
                      name="username"
                      class="form-control"
                      placeholder="your-email@gmail.com"
                      id="username"
                    />
                  </div>
                  <div class="form-group last mb-3">
                    <label for="password">Password</label>
                    <input
                      type="password"
                      class="form-control"
                      placeholder="Your Password"
                      id="password"
                      name="password"
                    />
                  </div>

                  <div class="d-sm-flex mb-5 align-items-center">
                    <label class="control control--checkbox mb-3 mb-sm-0"
                      ><span class="caption">Remember me</span> if you don't
                      have an account
                      <span
                        ><a href="{% url 'authentification:signup' %}"
                          >Register</a
                        ></span
                      >
                    </label>
                    <span class="ml-auto"
                      ><a href="#" class="forgot-pass">Forgot Password</a></span
                    >
                  </div>
                  <input
                    type="submit"
                    value="Log In"
                    class="btn btn-block py-2 btn-primary"
                  />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="{% static 'auth/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'auth/js/popper.min.js' %}"></script>
    <script src="{% static 'auth/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'auth/js/main.js' %}"></script>
  </body>
</html>

templates/register/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="{% static 'auth/fonts/icomoon/style.css' %}" />

    <link
      rel="stylesheet"
      href="{% static 'auth/css/owl.carousel.min.css' %}"
    />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'auth/css/bootstrap.min.css' %}" />

    <!-- Style -->
    <link rel="stylesheet" href="{% static 'auth/css/style.css' %}" />

    <title>Signup</title>
  </head>
  <body>
    <div class="d-md-flex half">
      <div
        class="bg"
        style="background-image: url('{% static 'auth/images/bg_1.jpg' %}')"
      ></div>
      <div class="contents">
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-12">
              <div class="form-block mx-auto">
                <div class="text-center mb-5">
                  <h3 class="text-uppercase">
                    Signup to <strong>Male-Fashion</strong>
                  </h3>
                </div>
                <form
                  action="{% url 'authentification:signup' %}"
                  method="POST"
                >
                  {% csrf_token %}

                  <div class="form-group">
                    <label for="username">Username:</label>
                    <input type="text" name="username" id="username" class="form-control" required>
                    {% if form.errors.username %}
                        <p class="text-danger">{{ form.errors.username }}</p>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="password1">Password:</label>
                    <input type="password" name="password1" id="password1" class="form-control" required>
                    {% if form.errors.password1 %}
                        <p class="text-danger">{{ form.errors.password1 }}</p>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="password2">Confirm Password:</label>
                    <input type="password" name="password2" id="password2" class="form-control" required>
                    {% if form.errors.password2 %}
                        <p class="text-danger">{{ form.errors.password2 }}</p>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" name="email" id="email" class="form-control" required>
                    {% if form.errors.email %}
                        <p class="text-danger">{{ form.errors.email }}</p>
                    {% endif %}
                </div>
            

                  <div class="d-sm-flex mb-5 align-items-center">
                    <label class="control control--checkbox mb-3 mb-sm-0"
                      >if you have an account
                      <span
                        ><a href="{% url 'authentification:signin' %}"
                          >Signin</a
                        ></span
                      >
                    </label>
                    <span class="ml-auto"
                      ><a href="#" class="forgot-pass">Forgot Password</a></span
                    >
                  </div>
                  <input
                    type="submit"
                    value="Sign Up"
                    class="btn btn-block py-2 btn-primary"
                  />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="{% static 'auth/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'auth/js/popper.min.js' %}"></script>
    <script src="{% static 'auth/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'auth/js/main.js' %}"></script>
  </body>
</html>