blogs/urls.py
from django.urls import path
from blogs.views import blog_search_view

app_name = 'blogs'

urlpatterns = [
    path('blog/', blog_search_view, name='blog_search')
]

conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('products/', include('products.urls', namespace='products')),
    path('auth/', include('authentification.urls', namespace='authentification')),
    path("blog/", include('blogs.urls', namespace='blogs')),
    path('orders/', include('orders.urls', namespace='orders')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders.views import OrderHistoryView, Proceed_Order, Detail_Info, CheckoutView
app_name = 'orders'

urlpatterns = [
    path('proceed_order/', Proceed_Order, name='proceed_order'),
    path("detail_info/", Detail_Info.as_view(), name='detail_info'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('history/', OrderHistoryView.as_view(), name='history'),
]

pages/urls.py
from django.urls import  path
# views
from pages.views import (PAGEHOMEVIEW,PAGEABOUTVIEW,PAGEBLOGDETAILVIEW, PAGEBLOGVIEW,PAGECONTACTVIEW,PAGESHOPVIEW, PageCommentView
)

app_name = 'pages'

urlpatterns = [
    path('', PAGEHOMEVIEW.as_view(), name='home' ),
    path('about/', PAGEABOUTVIEW.as_view(), name='about' ),
    path('<int:pk>/blog_detail/', PAGEBLOGDETAILVIEW.as_view(), name='blog_detail' ),
    path('blog/', PAGEBLOGVIEW.as_view(), name='blog' ),
    path('contact/', PAGECONTACTVIEW.as_view(), name='contact' ),
    path('shop/', PAGESHOPVIEW.as_view(), name='shop' ),
    path('comments/<int:pk>/', PageCommentView, name='comments')
]

products/urls.py
# imports 
from django.urls import path
from orders.views import add_cart_data
from products.views import (WishListView, add_to_wishlist,ProductDetailView, add_to_card, PAGESHOPCARTVIEW)

app_name = 'products'

urlpatterns = [
    path('wishlist/', WishListView.as_view(), name='wishlist'),
    path('<int:product_pk>/add_to_wishlist', add_to_wishlist, name= 'add_to_wishlist'),
    path('<int:pk>/shop_detail', ProductDetailView.as_view(),name= 'shop_details'),
    path('<int:pk>/add_to_card', add_to_card, name= 'add_to_card'),
    path('shop_cart/', PAGESHOPCARTVIEW.as_view(), name='shop_cart' ),
    path('<int:pk>/quantity/<int:quantity>', add_cart_data, name='add_cart_data')
]

blogs/models.py
from django.db import models
from products.models import TagsModel
# Create your models here.

class AuthorModel(models.Model):
    full_name = models.CharField(max_length=50)
    avatar = models.ImageField(upload_to='post/avatar')
    date_of_birth = models.DateField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self) :
        return self.full_name
    
    class Meta:
        verbose_name = 'Author'
        verbose_name_plural = 'Authors'



class PostModel(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    short_description = models.TextField()
    image = models.ImageField(upload_to='posts')
    tags = models.ManyToManyField(TagsModel)
    author = models.ForeignKey(AuthorModel, on_delete=models.CASCADE)
    

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_previous(self):
        return self.get_previous_by_created_at()
    
    def get_next(self):
        return self.get_next_by_created_at()
    
    def __str__(self) :
        return self.title
    
    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'



class MessageModel(models.Model):
    message = models.TextField()
    email = models.EmailField()
    phone = models.CharField(max_length=50,)
    name = models.CharField(max_length=40,)
    post = models.ForeignKey(PostModel, on_delete=models.CASCADE, related_name='message')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) :
        return self.message

    
    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'

blogs/views.py
from django.shortcuts import render
from django.views.generic import( DetailView, ListView)
from blogs.models import PostModel
# Create your views here.
def blog_search_view(request):
    q = request.GET.get('q')
    post = PostModel.objects.filter(tags_title__icontains=q)
    context = {'post': post}
    return render(request, 'blog.html', context=context)

templates/blog-details.html
{% extends 'layouts/base.html' %} {% load static %} {% block content %}
<!-- Blog Details Hero Begin -->
<section class="blog-hero spad">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-lg-9 text-center">
        <div class="blog__hero__text">
          <h2>{{ blog_detail.title }}</h2>
          <ul>
            <li>{{ blog_detail.author }}</li>
            <li>{{ blog_detail.created_at | date:'F d, Y ' }}</li>
            <li>{{blog_detail.message.all.count}} Comments</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Blog Details Hero End -->

<!-- Blog Details Section Begin -->
<section class="blog-details spad">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-lg-12">
        <div class="blog__details__pic">
          <img src="{{ blog_detail.image.url }}" alt="" />
        </div>
      </div>
      <div class="col-lg-8">
        <div class="blog__details__content">
          <div class="blog__details__share">
            <span>share</span>
            <ul>
              <li>
                <a href="#"><i class="fa fa-facebook"></i></a>
              </li>
              <li>
                <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              </li>
              <li>
                <a href="#" class="youtube"
                  ><i class="fa fa-youtube-play"></i
                ></a>
              </li>
              <li>
                <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
              </li>
            </ul>
          </div>
          <div class="blog__details__text">
            <p>{{ blog_detail.description }}</p>
            <p>{{ blog_detail.short_description }}</p>
          </div>

          <div class="blog__details__option">
            <div class="row">
              <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="blog__details__author">
                  <div class="blog__details__author__pic d-flex">
                    <img src="{{blog_detail.author.avatar.url}}" alt="" />
                    <p>{{blog_detail.author.full_name}}</p>
                  </div>
                </div>
              </div>
              <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="blog__details__tags">
                  {% for tag in blog_detail.tags.all %}
                  <a href="{% url 'pages:blog' %}?tag={{tag.title}}"
                    >#{{ tag.title }}</a
                  >
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
          <div class="blog__details__btns">
            <div class="row">
              <div class="col-lg-6 col-md-6 col-sm-6">
                {% if blog_detail.get_previous %}
                <a
                  href="{% url 'pages:blog_detail' pk=blog_detail.get_previous.pk %}"
                  class="blog__details__btns__item"
                >
                  <p><span class="arrow_left"></span> Previous Post</p>
                  <h5>{{ blog_detail.get_previous_by_created_at }}</h5>
                </a>
                {% endif %}
              </div>
              <div class="col-lg-6 col-md-6 col-sm-6">
                {% if blog_detail.get_next %}
                <a
                  href="{% url 'pages:blog_detail' pk=blog_detail.get_next.pk %}"
                  class="blog__details__btns__item blog__details__btns__item--next"
                >
                  <p>Next Post <span class="arrow_right"></span></p>
                  <h5>{{ blog_detail.get_next_by_created_at }}</h5>
                </a>
                {% endif %}
              </div>
            </div>
          </div>
          <div class="blog__details__comment">
            <h4>Leave A Comment</h4>
            <form
              method="POST"
              action="{% url 'pages:comments' pk=blog_detail.id %}"
            >
              {% csrf_token %}
              <div class="row">
                <div class="col-lg-4 col-md-4">
                  <label for="id_name">Name:</label>
                  <input
                    id="id_name"
                    name="name"
                    type="text"
                    placeholder="Name"
                  />
                </div>
                <div class="col-lg-4 col-md-4">
                  <label for="id_email">Email:</label>
                  <input
                    id="id_email"
                    name="email"
                    type="email"
                    placeholder="Email"
                  />
                </div>
                <div class="col-lg-4 col-md-4">
                  <label for="id_phone">Phone:</label>
                  <input
                    id="id_phone"
                    name="phone"
                    type="tel"
                    placeholder="Phone"
                  />
                </div>
                <div class="col-lg-12 text-center">
                  <label for="id_message">Comment:</label>
                  <textarea
                    id="id_message"
                    name="message"
                    placeholder="Comment"
                  ></textarea>
                  <button type="submit" class="site-btn">Post Comment</button>
                </div>
              </div>
            </form>
          </div>
          <!-- Blog Details Comment End -->
          <div class="blog-details-comment spad">
            <div class="container">
              <div class="row">
                <div class="col-lg-12">
                  {% if messages %}
                  <div class="alert alert-info">
                    <ul>
                      {% for message in messages %}
                      <li>{{ message }}</li>
                      {% endfor %}
                    </ul>
                  </div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
          <!-- Blog Details Comment End -->
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Blog Details Section End -->
{% endblock %}

templates/blog.html
{% extends 'layouts/base.html' %} {% load static %} {% block content %}
<!-- Breadcrumb Section Begin -->
<section
  class="breadcrumb-blog set-bg"
  data-setbg="{%static 'img/breadcrumb-bg.jpg'%}"
>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        {% if request.GET.tag %}
        <h2>#{{request.GET.tag}}</h2>
        {% else %}
        <h2>Our Blog</h2>
        {% endif %}
      </div>
    </div>
  </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Blog Section Begin -->
<section class="blog spad">
  <div class="container">
    <div class="row">
      {% for blog in blogs %}
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="blog__item">
          <div
            class="blog__item__pic set-bg"
            data-setbg="{{blog.image.url}}"
          ></div>
          <div class="blog__item__text">
            <span
              ><img src="{%static 'img/icon/calendar.png'%}" alt="" />
              {{blog.created_at | date:'F d, Y' }}</span
            >
            <h5>{{blog.title}}</h5>
            <a href="{% url 'pages:blog_detail' pk=blog.id %}">Read More</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- Blog Section End -->
{% endblock %}

templates/contact.html
{% extends 'layouts/base.html' %}
{% load static %} 
{% block content %}
<!-- Map Begin -->
<div class="map">
  <iframe
    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d111551.9926412813!2d-90.27317134641879!3d38.606612219170856!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54eab584e432360b%3A0x1c3bb99243deb742!2sUnited%20States!5e0!3m2!1sen!2sbd!4v1597926938024!5m2!1sen!2sbd"
    height="500"
    style="border: 0"
    allowfullscreen=""
    aria-hidden="false"
    tabindex="0"
  ></iframe>
</div>
<!-- Map End -->

<!-- Contact Section Begin -->
<section class="contact spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-6">
        <div class="contact__text">
          <div class="section-title">
            <span>Information</span>
            <h2>Contact Us</h2>
            <p>
              As you might expect of a company that began as a high-end
              interiors contractor, we pay strict attention.
            </p>
          </div>
          <ul>
            <li>
              <h4>America</h4>
              <p>
                195 E Parker Square Dr, Parker, CO 801 <br />+43 982-314-0958
              </p>
            </li>
            <li>
              <h4>France</h4>
              <p>109 Avenue Léon, 63 Clermont-Ferrand <br />+12 345-423-9893</p>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-lg-6 col-md-6">
        <div class="contact__form">
          <form action="{% url 'pages:contact' %}" method="POST">
            {% csrf_token %}
            <div class="row">
              <div class="col-lg-6">
                <input type="text" placeholder="name" name="name" />
              </div>
              <div class="col-lg-6">
                <input type="text" placeholder="email" name="email" />
              </div>
              <div class="col-lg-12">
                <textarea placeholder="message" name="message"></textarea>
                <button type="submit" class="site-btn">Send Message</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Contact Section End -->
{% endblock %}

templates/shop.html
{% extends 'layouts/base.html' %} {% block content %} {% load my_tags %} 
{% load static %}
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-option">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb__text">
          <h4>Shop</h4>
          <div class="breadcrumb__links">
            <a href="{% url 'pages:home' %}">Home</a>
            <span>Shop</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Shop Section Begin -->
<section class="shop spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <div class="shop__sidebar">
          <div class="shop__sidebar__search">
            <form method="GET">
              <input type="text" value="{{request.GET.q}}" name="q" placeholder="Search..." />
              <button type="submit"><span class="icon_search"></span></button>
            </form>
            <a href="{% url 'pages:shop' %}">Resert all research</a>
          </div>
          <div class="shop__sidebar__accordion">
            <div class="accordion" id="accordionExample">
              <div class="card">
                <div class="card-heading">
                  <a data-toggle="collapse" data-target="#collapseOne"
                    >Categories</a
                  >
                </div>
                <div
                  id="collapseOne"
                  class="collapse show"
                  data-parent="#accordionExample"
                >
                  <div class="card-body">
                    <div class="shop__sidebar__categories">
                      <ul class="nice-scroll">
                        {% for category in categories %}
                        <li>
                          <a href="{% url 'pages:shop'%}?category={{category.title}}"
                            >{{ category.title }}
                            ({{category.products.all.count}})</a
                          >
                        </li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card">
                <div class="card-heading">
                  <a data-toggle="collapse" data-target="#collapseTwo"
                    >Branding</a
                  >
                </div>
                <div
                  id="collapseTwo"
                  class="collapse show"
                  data-parent="#accordionExample"
                >
                  <div class="card-body">
                    <div class="shop__sidebar__brand">
                      <ul>
                        {% for brand in brands %}
                        <li><a href="{% url 'pages:shop'%}?brand={{brand.title}}">{{ brand.title }}</a></li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card">
                <div class="card-heading">
                  <a data-toggle="collapse" data-target="#collapseThree"
                    >Filter Price</a
                  >
                </div>
                <div
                  id="collapseThree"
                  class="collapse show"
                  data-parent="#accordionExample"
                >
                  <div class="card-body">
                    <div class="shop__sidebar__price">
                      <form method="GET">
                        <input type="number" placeholder="min price" name="min_price" id="min_price" value="{{ request.GET.min_price }}">
                        <input type="number" placeholder="max_price" name="max_price" id="max_price" value="{{ request.GET.max_price }}">
                        <button type="submit">Filter</button>
                    </form>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card">
                <div class="card-heading">
                  <a data-toggle="collapse" data-target="#collapseFour">Size</a>
                </div>
                <div
                  id="collapseFour"
                  class="collapse show"
                  data-parent="#accordionExample"
                >
                  <div class="card-body">
                    <div class="shop__sidebar__size">
                      {% for size in sizes %}
                        <a href="{% url 'pages:shop' %}?size={{size.title}}">
                          <label for="{{ size.title }}">  
                            {{ size.title }}
                          </label>
                        </a>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </div>
              <div class="card">
                <div class="card-heading">
                  <a data-toggle="collapse" data-target="#collapseFive"
                    >Colors</a
                  >
                </div>
                <div
                  id="collapseFive"
                  class="collapse show"
                  data-parent="#accordionExample"
                >
                  <div class="card-body">
                    <div class="shop__sidebar__color">
                      {% for color in colors %}
                      
                      <a href="{% url 'pages:shop' %}?color={{color.title}}">
                        <label
                        style="background-color: {{ color.code }};"
                        for="{{ color.title }}"
                      > 
                      </label></a>
                       
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </div>
              <div class="card">
                <div class="card-heading">
                  <a data-toggle="collapse" data-target="#collapseSix">Tags</a>
                </div>
                <div
                  id="collapseSix"
                  class="collapse show"
                  data-parent="#accordionExample"
                >
                  <div class="card-body">
                    <div class="shop__sidebar__tags">
                      {% for tag in tags %}
                      <a href="{% url 'pages:shop' %}?tags={{tag.title}}">{{ tag.title }}</a>
                      {% endfor %} 
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-9">
        <div class="shop__product__option">
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="shop__product__option__left">
                <p>Showing {{page_obj.number}} of {{page_obj.paginator.num_pages}} results</p>
              </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="shop__product__option__right">
                <p>Sort by Price:</p>
                <form method="GET">
                  <select name="sort" onchange="this.form.submit()">
                      {% if request.GET.sort %}
                          {% if request.GET.sort == "-price" %}
                              <option value="-price">High To Low</option>
                              <option value="price">Low To High</option>
                          {% else %}
                          <option value="price">Low To High</option>
                          <option value="-price">High To Low</option>
                          {% endif %}
                      {% else %}
                          <option value="price">Low To High</option>
                          <option value="-price">High To Low</option>
                      {% endif %}
              </select>
              </form>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          {% for product in products %}
          <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="product__item">
              <div
                class="product__item__pic set-bg"
                data-setbg="{{ product.image.url }}"
              >
              {% if product.is_new %}
                  <span class="label">New</span>  
              {% endif %}
              {% if product.discount %}
                  <span class="label bg-warning" style="margin-top: 30px;" >-{{product.discount}}%</span>
              {% endif %}
                <ul class="product__hover">
                  <li>
                    <a
                      href="{% url 'products:add_to_wishlist' product_pk=product.pk %}"
                    >
                      {% if request.user.is_authenticated %} 
                        {% if request.user|in_wishlist:product %}
                      <img src="{% static 'img/icon/heartr.png' %}" alt="" />
                        {% else %}
                      <img src="{% static 'img/icon/heart.png' %}" alt="" />
                        {% endif %} 
                      {% else %}
                      <img src="{% static 'img/icon/heart.png' %}" alt="" />
                      {% endif %}
                    </a>
                  </li>
                  
                  <li>
                    <a href="{% url 'products:shop_details' pk=product.pk %}"
                      ><img src="{% static 'img/icon/search.png' %}" alt=""
                    /></a>
                  </li> 
                </ul>
              </div>
              <div class="product__item__text">
                <h6>{{ product.name }}</h6>
                
                <a href="{% url 'products:add_to_card' pk=product.pk %}" class="add-cart">
                  {% if request|in_cart:product.pk %}
                  + Remove from Cart
                  {% else %}
                  + Add to Cart
                  {% endif %}
                </a>
                <div class="rating">
                  <i class="fa fa-star-o"></i>
                  <i class="fa fa-star-o"></i>
                  <i class="fa fa-star-o"></i>
                  <i class="fa fa-star-o"></i>
                  <i class="fa fa-star-o"></i>
                </div>
                <h5>
                  ${{ product.real_price }}
                  {% if product.discount %}
                  <span style="font-size:medium; color: red; margin-left: 5px;"><s>${{product.price}}</s></span>
                  {% endif %}
                </h5> 
                <div class="product__color__select">
                  {% for color in product.color.all %}
                  <label
                    class="active"
                    style="background-color: {{ color.code }};"
                    for="pc-4"
                  >
                    <input type="radio" id="pc-4" />
                  </label>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="product__pagination">
              
            {% if page_obj.has_previous %}
                <a class="" href="{% url 'pages:shop' %}?page={{page_obj.previous_page_number}}"><i class="fa-solid fa-arrow-left"></i></a>
            {% endif %}
            <a  class="active" href="{% url 'pages:shop' %}?page={{page_obj.number}}">{{page_obj.number}}</a>
            {% if page_obj.has_next %}
            <a class="" href="{% url 'pages:shop' %}?page={{page_obj.next_page_number}}"><i class="fa-solid fa-arrow-right"></i></a>
            {% endif %}

          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Shop Section End -->
{% endblock %}

templates/shopping-cart.html
{% extends 'layouts/base.html' %} 
{% load static %} 
{% load my_tags %}
{% block content %}
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-option">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb__text">
          <h4>Shopping Cart</h4>
          <div class="breadcrumb__links">
            <a href="{% url 'pages:home' %}">Home</a>
            <a href="{% url 'pages:shop' %}">Shop</a>
            <span>Shopping Cart</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Shopping Cart Section Begin -->
<section class="shopping-cart spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="shopping__cart__table">
          <table>
            <thead>
              <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Total</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% if products %}
              {% for product in products %}
              <form method="GET">
                {% csrf_token %}
                <tr>
                  <td class="product__cart__item">
                    <div class="product__cart__item__pic"  >
                      <img
                        src="{{product.image.url}}"
                        alt="""
                        width="100px"
                      />
                    </div>
                    <div class="product__cart__item__text">
                      <h6>{{product.name}}</h6>
                      <h5>${{product.real_price}} <span class="text-danger ml-3" ><s>${{product.price}}</s></span> </h5>
                    </div>
                  </td>
                  <td class="quantity__item">
                    <div class="quantity">
                      <div class="pro-qty-2">
                        <input name="quantity" type="submit" onclick="this.form.submit()" value="1" />
                      </div>
                    </div>
                  </td>
                  <td class="cart__price">${{product.price}}</td>
                  <td class="cart__close"><a href="{% url 'products:add_to_card' pk=product.pk %}"><i class="fa fa-close"></i></a></i></td>
                </tr>
              </form>
              {% endfor %}
              {% endif %}
            </tbody>
          </table>
        </div>
        
          <div class="row">
            {% if products %}
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="continue__btn">
                <a href="{% url 'pages:shop' %}">Continue Shopping</a>
              </div>
            </div>
            {% endif %}
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="continue__btn update__btn">
                    <a href=""><i class="fa fa-spinner"></i> Update cart</a>
                </div>
            </div>
        </div>
        
      </div>
      <div class="col-lg-4">
        <div class="cart__discount">
          <h6>Discount codes</h6>
          {% if not request.GET.coupon %}
          {% else %}
          {% if coupon %}
          {% cart_info request coupon as cart %}
          <div class="alert alert-success messages" role="alert">
              Coupon applied successfully! 
              You have {{ cart.0 }} items in your cart. 
              Your total price is {{ cart.1 }}.
          </div>

          {% else %}
          <div class="alert alert-danger messages" role="alert">
            Coupon didn't be applied successfully!
          </div>
          
          {% endif %}
          {% endif %}
          <form method="GET">
            <input name="coupon" type="text" placeholder="Coupon code" />
            <button type="submit">Apply</button>
          </form>
        </div>
        <div class="cart__total">
          <h6>Cart total</h6>
          <ul>
            {% for product in products %}
            <li>
              {{product.name|slice:'30'}} <span>${{product.real_price}}</span>
            </li>
            {% endfor %}

            {% cart_info request coupon as cart %}
            
            <li>Total <span> {{ cart.1  }}</span></li>
          </ul>
          <a href="{% url 'orders:checkout' %}?coupon={{coupon.code}}" class="primary-btn">Proceed to checkout</a>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Shopping Cart Section End -->
{% endblock %}
{% block extra_js %}
<script>
  setInterval(function(){ $(".alert").fadeOut(); }, 3000);
</script>
{% endblock %}